### ISSUE TITLE
review-1

### ISSUE THREAD

**Issue by yiminghe** [react-component/m-select-list#1]
## 参考 rc-select
1. pull 删除 node_modules 重装
2. lint 通过
3. locale: currentQf? 换个有意义的名字
4. 去除 value/defaultValue/onChange， 搜索框用户不需要关心
5. selectedItem 改名 value, defaultSelectedItem 换为 defaultValue，类型同 rc-select
6. onSelect 改名 onChange  
7. prefixCls rmc-select-list
8. util.js 拆分整理下
9. rmc-picker 也可以利用 overflow-scroll: touch 优化下

**Comment by pingan1927** [comment]
1、@yiminghe 说的是这个 -webkit-overflow-scrolling: touch;
2、搜索栏可以固定在顶部，list这个DOM的高度固定，同时设置第一点提的css
`this.refs.iscrollWrapper.style.height = (document.documentElement.clientHeight - serchBar's height) + 'px';
    this.refs.iscrollWrapper.style.overflowY = 'scroll';`
3、
![image](https://cloud.githubusercontent.com/assets/347649/13050234/fdf8e298-d42c-11e5-8473-fc3c4f58fa8a.png)
业务场景不仅仅是当前地区，或者current reigon，这个地方可以配置吗

**Comment by pingan1927** [comment]
1、有些场景是不需要searchBar的，可以隐藏吗？
2、有些场景search的trigger type可能不是onChange 而是虚拟键盘输入完内容后点击“搜索”进行触发。所以input的type最好设置为search，然后外面套一个form。

**Comment by yiminghe** [comment]
搜索框去掉吧，这个只做下面的列表

**Comment by warmhug** [comment]
搜索框代码也比较多，去掉要改动地方多，而且若以后有需求了再加，就麻烦了。

现在先把搜索框默认隐藏掉，也不对外公开API。

**Comment by yiminghe** [comment]
value 就是 value 就行了，和 rc-select 一样
onChange(value, item)
